#!/usr/bin/env python3
"""
Generate SKILL-INDEX.yaml by scanning the agent-v01/ directory tree.
Detects category based on parent directory name and auto-populates
technology tags where possible.
"""

import os
import yaml
from pathlib import Path

BASE_DIR = Path(__file__).parent.resolve()

# Category detection by parent directory name
CATEGORY_MAP = {
    "backend": "stack-backend",
    "frontend": "stack-frontend",
    "mobile": "stack-mobile",
    "cloud": "stack-cloud",
    "ai": "stack-ai",
    "agent-skills": "agent-skill",
    "supplements": "supplement",
    "methodologies": "methodology",
    "domains": "domain",
    "references": "reference",
    "protocols": "protocol",
}

# Default phase by category
PHASE_MAP = {
    "stack-backend": ["implementation"],
    "stack-frontend": ["implementation"],
    "stack-mobile": ["implementation"],
    "stack-cloud": ["implementation", "infrastructure"],
    "stack-ai": ["implementation"],
    "agent-skill": ["all"],
    "supplement": ["all"],
    "methodology": ["all"],
    "domain": ["all"],
    "reference": ["all"],
    "protocol": ["all"],
}


def scan_directory(base_path):
    """Scan the base path and build a skill index."""
    index = {}
    entries = []

    for entry in sorted(base_path.iterdir()):
        if entry.name.startswith(".") or entry.name.startswith("_"):
            continue
        if entry.is_dir():
            category = CATEGORY_MAP.get(entry.name, "unknown")
            phases = PHASE_MAP.get(category, ["all"])

            # Scan subdirectories
            subs = []
            for sub in sorted(entry.iterdir()):
                if sub.name.startswith("."):
                    continue
                if sub.is_symlink() or sub.is_dir():
                    rel_path = str(sub.relative_to(BASE_DIR))
                    skill_entry = {
                        "name": sub.name,
                        "path": rel_path,
                        "category": category,
                        "technologies": infer_technologies(sub.name),
                        "phases": phases,
                        "priority": infer_priority(category, sub.name),
                    }
                    subs.append(skill_entry)

            if subs:
                index[entry.name] = subs
                entries.extend(subs)

    return index, entries


def infer_technologies(name):
    """Infer likely technologies from directory name."""
    tech_map = {
        "nestjs": ["nestjs", "typescript", "nodejs"],
        "spring-boot": ["spring-boot", "java"],
        "java": ["java"],
        "golang": ["golang", "go"],
        "dot-net": ["dotnet", "csharp"],
        "react": ["react", "typescript", "javascript"],
        "nextjs": ["nextjs", "react", "typescript"],
        "vue": ["vue", "javascript"],
        "nuxt": ["nuxt", "vue", "javascript"],
        "ui-ux": ["ui", "ux", "design", "css"],
        "swift-ui": ["swift", "swiftui", "ios"],
        "android": ["android", "kotlin"],
        "kotlin-compose": ["kotlin", "compose", "jetpack"],
        "flutter": ["flutter", "dart"],
        "react-native": ["react-native", "javascript"],
        "aws": ["aws", "ecs", "lambda", "s3"],
        "azure": ["azure", "functions"],
        "langchain": ["langchain", "llm", "rag"],
        "mlflow": ["mlflow", "ml", "experiments"],
        "ml-agents": ["machine-learning", "agents"],
        "context-engineering": ["context", "prompt", "llm"],
        "ecommerce": ["ecommerce", "shopify", "payments"],
    }
    return tech_map.get(name, [name])


def infer_priority(category, name):
    """Infer priority based on category and name."""
    high_priority_categories = {"stack-backend", "stack-frontend", "agent-skill"}
    if category in high_priority_categories:
        if "dev" in name or "architect" in name or "review" in name or "qa" in name:
            return "high"
        return "medium"
    if category == "stack-cloud":
        return "high" if "aws" in name else "medium"
    if category == "supplement":
        if "system-design" in name or "code-review" in name:
            return "high"
        return "medium"
    return "low"


def main():
    index, entries = scan_directory(BASE_DIR)

    output = {
        "# agent-v01 Skill Index": "Auto-generated by generate-skill-index.py",
        "generated_at": "2026-07-30",
    }
    output.update(index)

    print(yaml.dump(output, default_flow_style=False, sort_keys=False))
    print(f"\n# Total entries: {len(entries)}", file=__import__('sys').stderr)


if __name__ == "__main__":
    main()
